### ISSUE TITLE
image preview

### ISSUE THREAD

**Issue by sassanh** [airodactyl/neovim-ranger#1]
Thanks for this extension, it solves common problems with `neovim` though it doesn't show image previews (I'm testing it in ITerm) it'd be great if you could introduce a workaround for image previews too.

**Comment by Enzime** [comment]
I'll have to look into running `ranger` on OS X. As of now, I can run `ranger` on OS X but I haven't yet gotten iTerm 2's image display working in `ranger`. Have you tested to make sure that `ranger` (without `tmux`) displays the image preview?

**Comment by sassanh** [comment]
@Enzime yes, `ranger` itself displays images. I'm using Iterm2 - Build 3.0.4 and I had to add these lines to `rc.conf`:

```
set preview_images true
set preview_images_method iterm2
```
