### ISSUE TITLE
No selectable folders / icons when opening directory

### ISSUE THREAD

**Issue by bergercookie** [airodactyl/neovim-ranger#4]
I am running the latest version of neovim-ranger and I'm using neovim v0.2.2 and ranger 1.9.1. When I open a directory from neovim I get the following page where None of the files / directories is selectable. Furthermore I cannot seem to navigate as in the standard ranger. It's pretty obvious that this is not the way the plugin was designed to work. Any pointers on why this may be happening?

![1](https://user-images.githubusercontent.com/5816719/39970957-a30a3762-56eb-11e8-9107-bd55e6f3efeb.png)

Vim configuration: https://github.com/bergercookie/vim-dotfiles/blob/master/.vimrc
ranger configuration: [rc.txt](https://github.com/airodactyl/neovim-ranger/files/1998840/rc.txt)

**Comment by Enzime** [comment]
In neovim, the terminal mode requires you to enter Insert mode before you can send keypresses to ranger
